version: 2.0

jobs:
  lint:
    docker:
      - image: node:10.16.0-alpine
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  test:
    docker:
      - image: node:10.16.0-alpine
    steps:
      - checkout
      - run: npm i
      - run: npm test
  build:
    docker:
      - image: node:10.16.0-alpine
    steps:
      - checkout
      - run: npm i
      - run: npm run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - build:
          requires:
            - test
