version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/node:10.16.0-alpine
    steps:
      - checkout
      - run:
        name: Install npm
        command: npm i
      - run:
        name: Run lint
        command: npm run lint
  test:
    docker:
      - image: circleci/node:10.16.0-alpine
    steps:
      - checkout
      - run:
        name: Install npm
        command: npm i
      - run:
        name: Run test
        command: npm test
  build:
    docker:
      - image: circleci/node:10.16.0-alpine
    steps:
      - checkout
      - run:
        name: Install npm
        command: npm i
      - run:
        name: Run build
        command: npm run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test:
        requires:
          - lint
      - build:
        requires:
          - test
